version: "2.1"

networks:
  app-tier:
    driver: bridge

services:
  c3:
    container_name: c3
    image: gateguardai/c3:v1.0.0
    command: "sleep infinity"
    ports:
      - 9000:9000
    volumes:
      - /run/jtop.sock:/run/jtop.sock
      - /data:/data

